name: Build Microservices

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  detect-changes:
    name: Detect Service Changes
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.check.outputs.config }}
      gateway: ${{ steps.check.outputs.gateway }}
      eureka: ${{ steps.check.outputs.eureka }}
      auth: ${{ steps.check.outputs.auth }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed folders
        id: check
        run: |
          git fetch origin ${{ github.event.before }}  # Eski commit'i indir
          
          
          if ! git rev-parse --verify ${{ github.event.before }} >/dev/null 2>&1; then
            echo "Eski commit bulunamadı, tüm dosyaları değişmiş say."
            CONFIG_CHANGED=1
            GATEWAY_CHANGED=1
            EUREKA_CHANGED=1
            AUTH_CHANGED=1
          else
            CONFIG_CHANGED=$(git diff --name-only 7de859cb4867245a139c26e898b3baff3de8e42a 4b0139714daf3579bb29e0613a1a30aa9a928e5a | grep -c '^fun-config-service/')
            GATEWAY_CHANGED=$(git diff --name-only 7de859cb4867245a139c26e898b3baff3de8e42a 4b0139714daf3579bb29e0613a1a30aa9a928e5a | grep -c '^fun-gateway-service/')
            EUREKA_CHANGED=$(git diff --name-only 7de859cb4867245a139c26e898b3baff3de8e42a 4b0139714daf3579bb29e0613a1a30aa9a928e5a | grep -c '^fun-eureka-service/')
            AUTH_CHANGED=$(git diff --name-only 7de859cb4867245a139c26e898b3baff3de8e42a 4b0139714daf3579bb29e0613a1a30aa9a928e5a | grep -c '^fun-auth-service/')
          fi
  
          echo "config=$CONFIG_CHANGED" >> $GITHUB_OUTPUT
          echo "gateway=$GATEWAY_CHANGED" >> $GITHUB_OUTPUT
          echo "eureka=$EUREKA_CHANGED" >> $GITHUB_OUTPUT
          echo "auth=$AUTH_CHANGED" >> $GITHUB_OUTPUT

  call-gateway-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.gateway != '0'
    uses: ./.github/workflows/fun-gateway-service.yml

  call-eureka-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.eureka != '0'
    uses: ./.github/workflows/fun-eureka-service.yml

  call-config-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.config != '0'
    uses: ./.github/workflows/fun-config-service.yml

  call-auth-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.auth != '0'
    uses: ./.github/workflows/fun-auth-service.yml